version: 2

models:
  - name: stg__fhv_bases
    description: "This table contains data about For-Hire Vehicle (FHV) bases, including their names and operational details."
    columns:
      - name: base_number
        data_type: varchar
        description: "The unique number assigned to each FHV base."
        tests:
          - not_null
          - unique
      - name: base_name
        data_type: varchar
        description: "The name of the FHV base."
        tests:
          - not_null
      - name: doing_business_as
        data_type: varchar
        description: "The name under which the base operates, often different from the official base name."
        tests:
          - not_null
      - name: doing_business_as_category
        data_type: varchar
        description: "The category of business under which the FHV base operates."
      - name: filename
        data_type: varchar
        description: "The name of the file from which this data was ingested."

  - name: stg__fhv_tripdata
    description: "This table contains trip data for For-Hire Vehicles (FHVs), detailing trip times, locations, and other trip-specific information."
    columns:
      - name: dispatching_base_num
        data_type: varchar
        description: "The base number that dispatched the trip."
        tests:
          - not_null
      - name: pickup_datetime
        data_type: timestamp
        description: "The datetime when the trip was picked up."
        tests:
          - not_null
      - name: dropoff_datetime
        data_type: timestamp
        description: "The datetime when the trip was dropped off."
        tests:
          - not_null
      - name: pickup_location_id
        data_type: integer
        description: "The location ID where the trip was picked up."
        tests:
          - not_null
      - name: dropoff_location_id
        data_type: integer
        description: "The location ID where the trip was dropped off."
        tests:
          - not_null
      - name: shared_ride_flag
        data_type: integer
        description: "Indicates whether the ride was shared."
      - name: affiliated_base_number
        data_type: varchar
        description: "The base number affiliated with the trip, which may differ from the dispatching base."
      - name: filename
        data_type: varchar
        description: "The name of the file from which this data was ingested."

  - name: stg__fhvhv_tripdata
    description: "This table contains trip data for high-volume For-Hire Vehicles (FHVs), including details on trip times, locations, and fares."
    columns:
      - name: hvfhs_license_num
        data_type: varchar
        description: "The license number of the high-volume FHV service."
        tests:
          - not_null
          - unique
      - name: dispatching_base_num
        data_type: varchar
        description: "The base number that dispatched the trip."
      - name: originating_base_num
        data_type: varchar
        description: "The base number where the trip originated."
      - name: request_datetime
        data_type: timestamp
        description: "The datetime when the trip was requested."
      - name: on_scene_datetime
        data_type: timestamp
        description: "The datetime when the vehicle arrived on scene."
      - name: pickup_datetime
        data_type: timestamp
        description: "The datetime when the trip was picked up."
        tests:
          - not_null
      - name: dropoff_datetime
        data_type: timestamp
        description: "The datetime when the trip was dropped off."
      - name: pickup_location_id
        data_type: integer
        description: "The location ID where the trip was picked up."
      - name: dropoff_location_id
        data_type: integer
        description: "The location ID where the trip was dropped off."
      - name: trip_miles
        data_type: double
        description: "The distance of the trip in miles."
      - name: trip_time
        data_type: integer
        description: "The duration of the trip in seconds."
      - name: base_passenger_fare
        data_type: double
        description: "The base fare charged to the passenger."
      - name: tolls
        data_type: double
        description: "The amount of tolls paid during the trip."
      - name: bcf
        data_type: double
        description: "The Black Car Fund fee."
      - name: sales_tax
        data_type: double
        description: "The amount of sales tax applied to the fare."
      - name: congestion_surcharge
        data_type: double
        description: "The congestion surcharge applied to the fare."
      - name: tips
        data_type: double
        description: "The amount of tips given by the passenger."
      - name: driver_pay
        data_type: double
        description: "The amount paid to the driver."
      - name: shared_request_flag
        data_type: boolean
        description: "Indicates whether the trip was a shared ride request."
      - name: shared_match_flag
        data_type: boolean
        description: "Indicates whether the shared ride request was matched."
      - name: access_a_ride_flag
        data_type: boolean
        description: "Indicates whether the trip was an Access-A-Ride trip."
      - name: wav_request_flag
        data_type: boolean
        description: "Indicates whether the trip was a Wheelchair Accessible Vehicle (WAV) request."
      - name: wav_match_flag
        data_type: boolean
        description: "Indicates whether the WAV request was matched."
      - name: filename
        data_type: varchar
        description: "The name of the file from which this data was ingested."

  - name: stg__bike_data
    description: "This table contains data from the Citibike trip records, detailing various bike trips including duration, start and end locations, and user information."
    columns:
      - name: trip_duration
        data_type: integer
        description: "The duration of the bike trip in seconds."
        tests:
          - not_null
      - name: start_time
        data_type: timestamp
        description: "The exact timestamp when the bike trip started."
        tests:
          - not_null
      - name: stop_time
        data_type: timestamp
        description: "The exact timestamp when the bike trip ended."
        tests:
          - not_null
      - name: start_station_id
        data_type: integer
        description: "The unique identifier for the station where the bike trip started."
      - name: start_station_name
        data_type: varchar
        description: "The name of the station where the bike trip started."
      - name: start_station_lat
        data_type: double
        description: "The latitude coordinate of the start station."
      - name: start_station_lng
        data_type: double
        description: "The longitude coordinate of the start station."
      - name: end_station_id
        data_type: integer
        description: "The unique identifier for the station where the bike trip ended."
      - name: end_station_name
        data_type: varchar
        description: "The name of the station where the bike trip ended."
      - name: end_station_lat
        data_type: double
        description: "The latitude coordinate of the end station."
      - name: end_station_lng
        data_type: double
        description: "The longitude coordinate of the end station."
      - name: bike_id
        data_type: integer
        description: "The unique identifier for the bike used in the trip."
        tests:
          - not_null
          - unique
      - name: user_type
        data_type: varchar
        description: "The type of user, indicating whether the user is a subscriber or a casual customer."
      - name: birth_year
        data_type: integer
        description: "The birth year of the user."
      - name: gender
        data_type: integer
        description: "The gender of the user, represented as an integer."
        tests:
          - accepted_values:
              values: [0, 1, 2]
      - name: filename
        data_type: varchar
        description: "The name of the file from which this data was ingested."

  - name: stg__central_park_weather
    description: "This table contains weather data for Central Park, including various weather metrics recorded at different times."
    columns:
      - name: station
        data_type: varchar
        description: "The unique identifier for the weather station that recorded the data."
        tests:
          - not_null
          - unique
      - name: station_name
        data_type: varchar
        description: "The name of the weather station."
        tests:
          - not_null
      - name: observation_date
        data_type: date
        description: "The date when the weather observation was made."
        tests:
          - not_null
      - name: average_wind_speed
        data_type: double
        description: "The average wind speed recorded on the observation date."
      - name: precipitation
        data_type: double
        description: "The amount of precipitation recorded on the observation date."
      - name: snowfall
        data_type: double
        description: "The amount of snowfall recorded on the observation date."
      - name: snow_depth
        data_type: double
        description: "The depth of snow on the ground recorded on the observation date."
      - name: max_temperature
        data_type: integer
        description: "The maximum temperature recorded on the observation date."
      - name: min_temperature
        data_type: integer
        description: "The minimum temperature recorded on the observation date."
      - name: filename
        data_type: varchar
        description: "The name of the file from which this data was ingested."
