version: 2

sources:
  - name: main
    description: >
      This is the database that we ingested all raw data into for the class cmu_95797.
    tables:
      - name: bike_data
        description: >
          This table contains data from the Citibike trip records, detailing various bike trips including duration, start and end locations, and user information.
        columns:
          - name: trip_duration
            description: >
              The duration of the bike trip in seconds.
            data_type: varchar
          - name: start_time
            description: >
              The exact timestamp when the bike trip started.
            data_type: varchar
          - name: stop_time
            description: >
              The exact timestamp when the bike trip ended.
            data_type: varchar
          - name: start_station_id
            description: >
              The unique identifier for the station where the bike trip started.
            data_type: varchar
          - name: end_station_id
            description: >
              The unique identifier for the station where the bike trip ended.
            data_type: varchar
          - name: start_station_lat
            description: >
              The latitude coordinate of the start station.
            data_type: varchar
          - name: start_station_lng
            description: >
              The longitude coordinate of the start station.
            data_type: varchar
          - name: end_station_lat
            description: >
              The latitude coordinate of the end station.
            data_type: varchar
          - name: end_station_lng
            description: >
              The longitude coordinate of the end station.
            data_type: varchar
          - name: bike_id
            description: >
              The unique identifier for the bike used in the trip.
            data_type: varchar
          - name: birth_year
            description: >
              The birth year of the user.
            data_type: varchar
          - name: gender
            description: >
              The gender of the user, represented as an integer.
            data_type: varchar

      - name: central_park_weather
        description: >
          This table contains weather data for Central Park, including various weather metrics recorded at different times.
        columns:
          - name: station
            description: >
              The unique identifier for the weather station that recorded the data.
            data_type: varchar
          - name: average_wind_speed
            description: >
              The average wind speed recorded on the observation date.
            data_type: varchar
          - name: snowfall
            description: >
              The amount of snowfall recorded on the observation date.
            data_type: varchar
          - name: max_temperature
            description: >
              The maximum temperature recorded on the observation date.
            data_type: varchar

      - name: fhv_bases
        description: >
          This table contains data about For-Hire Vehicle (FHV) bases, including their names and operational details.
        columns:
          - name: base_number
            description: >
              The unique number assigned to each FHV base.
            data_type: varchar
          - name: base_name
            description: >
              The name of the FHV base.
            data_type: varchar

      - name: fhv_tripdata
        description: >
          This table contains trip data for For-Hire Vehicles (FHVs), detailing trip times, locations, and other trip-specific information.
        columns:
          - name: dispatching_base_num
            description: >
              The base number that dispatched the trip.
            data_type: varchar
          - name: pickup_datetime
            description: >
              The datetime when the trip was picked up.
            data_type: timestamp
          - name: dropoff_datetime
            description: >
              The datetime when the trip was dropped off.
            data_type: timestamp
          - name: pickup_location_id
            description: >
              The location ID where the trip was picked up.
            data_type: double
          - name: dropoff_location_id
            description: >
              The location ID where the trip was dropped off.
            data_type: double
          - name: shared_ride_flag
            description: >
              Indicates whether the ride was shared.
            data_type: integer
          - name: affiliated_base_number
            description: >
              The base number affiliated with the trip, which may differ from the dispatching base.
            data_type: varchar

      - name: fhvhv_tripdata
        description: >
          This table contains trip data for high-volume For-Hire Vehicles (FHVs), including details on trip times, locations, and fares.
        columns:
          - name: hvfhs_license_num
            description: >
              The license number of the high-volume FHV service.
            data_type: varchar
          - name: request_datetime
            description: >
              The datetime when the trip was requested.
            data_type: timestamp
          - name: on_scene_datetime
            description: >
              The datetime when the vehicle arrived on scene.
            data_type: timestamp
          - name: pickup_datetime
            description: >
              The datetime when the trip was picked up.
            data_type: timestamp
          - name: dropoff_datetime
            description: >
              The datetime when the trip was dropped off.
            data_type: timestamp
          - name: trip_miles
            description: >
              The distance of the trip in miles.
            data_type: double
          - name: trip_time
            description: >
              The duration of the trip in seconds.
            data_type: bigint
          - name: base_passenger_fare
            description: >
              The base fare charged to the passenger.
            data_type: double
          - name: tips
            description: >
              The amount of tips given by the passenger.
            data_type: double

      - name: green_tripdata
        description: >
          This table contains trip data for green cabs, detailing trip times, locations, fares, and passenger information.
        columns:
          - name: vendor_id
            description: >
              The unique identifier for the vendor providing the green cab service.
            data_type: bigint
          - name: pickup_datetime
            description: >
              The datetime when the trip was picked up.
            data_type: timestamp
          - name: dropoff_datetime
            description: >
              The datetime when the trip was dropped off.
            data_type: timestamp
          - name: store_and_fwd_flag
            description: >
              A flag indicating whether the trip data was stored and forwarded due to the vehicle being outside the service area.
            data_type: varchar
          - name: rate_code_id
            description: >
              The rate code applicable to the trip.
            data_type: double
          - name: pu_location_id
            description: >
              The location ID where the trip was picked up.
            data_type: bigint
          - name: do_location_id
            description: >
              The location ID where the trip was dropped off.
            data_type: bigint
          - name: passenger_count
            description: >
              The number of passengers in the trip.
            data_type: double
          - name: trip_distance
            description: >
              The distance of the trip in miles.
            data_type: double
          - name: fare_amount
            description: >
              The fare amount charged for the trip.
            data_type: double
          - name: extra
            description: >
              Additional charges applied to the fare, such as surcharges and tolls.
            data_type: double
          - name: mta_tax
            description: >
              The Metropolitan Transportation Authority (MTA) tax applied to the fare.
            data_type: double
          - name: tip_amount
            description: >
              The amount of tips given by the passenger.
            data_type: double
          - name: tolls_amount
            description: >
              The amount of tolls paid during the trip.
            data_type: double
          - name: improvement_surcharge
            description: >
              The improvement surcharge applied to the fare.
            data_type: double
          - name: total_amount
            description: >
              The total fare amount including all charges and surcharges.
            data_type: double
          - name: payment_type
            description: >
              The type of payment used for the trip (e.g., credit card, cash).
            data_type: double
          - name: trip_type
            description: >
              The type of trip (e.g., street-hail, prearranged).
            data_type: double
          - name: congestion_surcharge
            description: >
              The congestion surcharge applied to the fare.
            data_type: double
          - name: filename
            description: >
              The name of the file from which this data was ingested.
            data_type: varchar

      - name: yellow_tripdata
        description: >
          This table contains trip data for yellow cabs, detailing trip times, locations, fares, and passenger information.
        columns:
          - name: vendor_id
            description: >
              The unique identifier for the vendor providing the yellow cab service.
            data_type: bigint
          - name: pickup_datetime
            description: >
              The datetime when the trip was picked up.
            data_type: timestamp
          - name: dropoff_datetime
            description: >
              The datetime when the trip was dropped off.
            data_type: timestamp
          - name: passenger_count
            description: >
              The number of passengers in the trip.
            data_type: double
          - name: trip_distance
            description: >
              The distance of the trip in miles.
            data_type: double
          - name: fare_amount
            description: >
              The fare amount charged for the trip.
            data_type: double
          - name: tolls_amount
            description: >
              The amount of tolls paid during the trip.
            data_type: double
